# PROJECT -3. BOOKING

Первоначальная версия датасета содержит 17 полей со следующей информацией:

hotel_address — адрес отеля;
review_date — дата, когда рецензент разместил соответствующий отзыв;
average_score — средний балл отеля, рассчитанный на основе последнего комментария за последний год;
hotel_name — название отеля;
reviewer_nationality — страна рецензента;
negative_review — отрицательный отзыв, который рецензент дал отелю;
review_total_negative_word_counts — общее количество слов в отрицательном отзыв;
positive_review — положительный отзыв, который рецензент дал отелю;
review_total_positive_word_counts — общее количество слов в положительном отзыве.
reviewer_score — оценка, которую рецензент поставил отелю на основе своего опыта;
total_number_of_reviews_reviewer_has_given — количество отзывов, которые рецензенты дали в прошлом;
total_number_of_reviews — общее количество действительных отзывов об отеле;
tags — теги, которые рецензент дал отелю;
days_since_review — количество дней между датой проверки и датой очистки;
additional_number_of_scoring — есть также некоторые гости, которые просто поставили оценку сервису, но не оставили отзыв. Это число указывает, сколько там действительных оценок без проверки.
lat — географическая широта отеля;
lng — географическая долгота отеля.

In [85]:
#ЗАГРУЗИМ ДАННЫЕ

import pandas as pd

hotels = pd.read_csv('hotels.csv')
hotels.head(2)

,hotel_address,additional_number_of_scoring,review_date,average_score,hotel_name,reviewer_nationality,negative_review,review_total_negative_word_counts,total_number_of_reviews,positive_review,review_total_positive_word_counts,total_number_of_reviews_reviewer_has_given,reviewer_score,tags,days_since_review,lat,lng
0,Stratton Street Mayfair Westminster Borough Lo...,581,2/19/2016,8.4,The May Fair Hotel,United Kingdom,Leaving,3,1994,Staff were amazing,4,7,10.0,"[' Leisure trip ', ' Couple ', ' Studio Suite ...",531 day,51.507894,-0.143671
1,130 134 Southampton Row Camden London WC1B 5AF...,299,1/12/2017,8.3,Mercure London Bloomsbury Hotel,United Kingdom,poor breakfast,3,1361,location,2,14,6.3,"[' Business trip ', ' Couple ', ' Standard Dou...",203 day,51.521009,-0.123097

In [86]:
# В каких столбцах данные содержат пропущенные значения?
#В каких столбцах данные хранятся в числовом формате?
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386803 entries, 0 to 386802
Data columns (total 17 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   hotel_address                               386803 non-null  object
 1   additional_number_of_scoring                386803 non-null  int64
 2   review_date                                 386803 non-null  object
 3   average_score                               386803 non-null  float64
 4   hotel_name                                  386803 non-null  object
 5   reviewer_nationality                        386803 non-null  object
 6   negative_review                             386803 non-null  object
 7   review_total_negative_word_counts           386803 non-null  int64
 8   total_number_of_reviews                     386803 non-null  int64
 9   positive_review                             386803 non-null  object
 10  review_total_positive_word_counts           386803 non-null  int64
 11  total_number_of_reviews_reviewer_has_given  386803 non-null  int64
 12  reviewer_score                              386803 non-null  float64
 13  tags                                        386803 non-null  object
 14  days_since_review                           386803 non-null  object
 15  lat                                         384355 non-null  float64
 16  lng                                         384355 non-null  float64
dtypes: float64(4), int64(5), object(8)
memory usage: 50.2+ MB

Задачу, которая стоит перед вами, можно свести к пяти пунктам:

Удаление строковых значений. Вам необходимо удалить из набора данных столбцы, данные в которых представлены не числами.
Очистка от пропущенных значений. На предыдущем шаге мы делали это самым грубым из всех возможных способов, сейчас попробуйте подойти к процессу более гибко.
Создание новых признаков. Мы попробуем создать новые столбцы с данными из существующих данных или с использованием внешних источников.
Преобразование признаков. Применим различные преобразования над признаками вроде нормализации, стандартизации.
Отбор признаков. Используем анализ мультиколлинеарности как шаг отбора признаков для модели.

In [87]:
# Сколько уникальных названий отелей представлено в наборе данных?
hotels['hotel_name'].nunique()

1492

In [88]:
hotels['review_date'] = pd.to_datetime(hotels['review_date'], dayfirst=False)

In [89]:
# Когда был оставлен самый свежий отзыв? Введите ответ в формате yyyy-mm-dd.
# Когда был оставлен самый первый отзыв? Введите ответ в формате yyyy-mm-dd.
display(hotels['review_date'].max())
display(hotels['review_date'].min())

Timestamp('2017-08-03 00:00:00')

Timestamp('2015-08-04 00:00:00')

In [239]:
# Сколько уникальных тегов представлено в наборе данных?

6

In [240]:
#посчитаем количество тегов (это кол-во запятых между ними+1)
hotels['tags_num'] = hotels['tags'].str.count(',')+1
hotels['tags_num'].describe()

count    386803.000000
mean          4.569566
std           0.520163
min           1.000000
25%           4.000000
50%           5.000000
75%           5.000000
max           6.000000
Name: tags_num, dtype: float64

In [389]:
#обработаем теги
new_tags = hotels['tags'].str.replace(" ']", '')
new_tags = new_tags.str.replace("[' ", '')
new_tags = new_tags.str.replace("' ", '')
new_tags = new_tags.str.replace(" '", '')


tags_a= pd.DataFrame()
tags_a['tags'] = new_tags.astype(str)

#с животными
tags_a['pet'] = tags_a['tags'].apply(lambda x: x.split(', ')[0] if x.split(', ')[0] == 'With a pet' else 'No pet')
tags_a['cleaned_tags'] = tags_a['tags'].str.replace('With a pet, ', '')
#с мобильного
tags_a['device'] = tags_a['tags'].apply(lambda x: x.split(', ')[-1] if x.split(', ')[-1] == 'Submitted from a mobile device' else 'other')
tags_a['cleaned_tags'] = tags_a['cleaned_tags'].str.replace(', Submitted from a mobile device', '')

#команировка/отдых
tags_a['trip_type'] = tags_a['cleaned_tags'].apply(lambda x: x.split(', ')[0] if x.split(', ')[0] == 'Leisure trip' or x.split(', ')[0] == 'Business trip'  else 'other')
tags_a['cleaned_tags'] = tags_a['cleaned_tags'].str.replace('Leisure trip, ', '')
tags_a['cleaned_tags'] = tags_a['cleaned_tags'].str.replace('Business trip, ', '')

#компания
tags_a['traveler'] = tags_a['cleaned_tags'].apply(lambda x: x.split(', ')[0])
list_of_rep = ['Couple,', 'Solo traveler', 'Family with young children', 'Group',
       'Family with older children', 'Travelers with friends']

tags_a['cleaned_tags'] = tags_a['cleaned_tags'].replace(list_of_rep, '')




#срок пребывания (в строке попались некоторые ошибки, которые можно вычистить)
tags_a['duration_of_stay'] = tags_a['cleaned_tags'].apply(lambda x: x.split(', ')[-1])
#чтобы вычистить ошибки, очистим инфорацию и оставим только числовое значение кол-ва ночей
tags_a['number_of_days'] = tags_a['duration_of_stay'].str.extract('(\d+)', expand=False)


#добавим информацию о кол-ве тегов
tags_a['tags_num'] = hotels['tags'].str.count(',')+1

tags_a

,tags,pet,cleaned_tags,device,trip_type,traveler,tags_num,duration_of_stay
0,"Leisure trip, Couple, Studio Suite, Stayed 2 n...",No pet,"Couple, Studio Suite, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Couple,5,Stayed 2 nights
1,"Business trip, Couple, Standard Double Room, S...",No pet,"Couple, Standard Double Room, Stayed 1 night",other,Business trip,Couple,4,Stayed 1 night
2,"Leisure trip, Solo traveler, Modern Double Roo...",No pet,"Solo traveler, Modern Double Room Echo, Stayed...",Submitted from a mobile device,Leisure trip,Solo traveler,5,Stayed 3 nights
3,"Leisure trip, Solo traveler, Standard Room wit...",No pet,"Solo traveler, Standard Room with 1 Double Bed...",other,Leisure trip,Solo traveler,4,Stayed 1 night
4,"Business trip, Couple, Standard Double or Twin...",No pet,"Couple, Standard Double or Twin Room, Stayed 6...",other,Business trip,Couple,4,Stayed 6 nights
...,...,...,...,...,...,...,...,...
386798,"Leisure trip, Group, Club Double or Twin Room,...",No pet,"Group, Club Double or Twin Room, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Group,5,Stayed 2 nights
386799,"Leisure trip, Couple, Standard Double Room, St...",No pet,"Couple, Standard Double Room, Stayed 4 nights",Submitted from a mobile device,Leisure trip,Couple,5,Stayed 4 nights
386800,"Business trip, Solo traveler, Single Room, Sta...",No pet,"Solo traveler, Single Room, Stayed 1 night",other,Business trip,Solo traveler,4,Stayed 1 night
386801,"Leisure trip, Solo traveler, Deluxe Double Roo...",No pet,"Solo traveler, Deluxe Double Room, Stayed 2 ni...",other,Leisure trip,Solo traveler,4,Stayed 2 nights
386802,"Leisure trip, Couple, Bunk Bed Room, Stayed 4 ...",No pet,"Couple, Bunk Bed Room, Stayed 4 nights",other,Leisure trip,Couple,4,Stayed 4 nights

In [385]:
tags_a[tags_a['tags_num']==2]['cleaned_tags']

1865
25450
33053     Couple
54240     Couple
56081
           ...
358001
373516
375091    Couple
382344
384943    Couple
Name: cleaned_tags, Length: 65, dtype: object

In [378]:
list_of_rep = ['Couple', 'Solo traveler', 'Family with young children', 'Group',
       'Family with older children', 'Travelers with friends']

tags_a['cleaned_tags'] = tags_a['cleaned_tags'].replace(list_of_rep, '')


tags_a['cleaned_tags'] = tags_a['cleaned_tags'].apply(lambda word: for word in list_of_rep  replace('word', '') )

In [393]:
tags_a['duration_of_stay'].unique()

tags_a['number_of_days'] = tags_a['duration_of_stay'].str.extract('(\d+)', expand=False)

tags_a['number_of_days']

0         2
1         1
2         3
3         1
4         6
         ..
386798    2
386799    4
386800    1
386801    2
386802    4
Name: number_of_days, Length: 386803, dtype: object

In [396]:
tags_a[tags_a['duration_of_stay']== 'Stayed 2 nights']

,tags,pet,cleaned_tags,device,trip_type,traveler,tags_num,duration_of_stay,number_of_days
0,"Leisure trip, Couple, Studio Suite, Stayed 2 n...",No pet,"Couple, Studio Suite, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Couple,5,Stayed 2 nights,2
17,"Leisure trip, Group, Standard Room, Stayed 2 n...",No pet,"Group, Standard Room, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Group,5,Stayed 2 nights,2
18,"Leisure trip, Solo traveler, Standard Double R...",No pet,"Solo traveler, Standard Double Room, Stayed 2 ...",other,Leisure trip,Solo traveler,4,Stayed 2 nights,2
21,"Business trip, Solo traveler, Executive Double...",No pet,"Solo traveler, Executive Double Room, Stayed 2...",other,Business trip,Solo traveler,4,Stayed 2 nights,2
25,"Leisure trip, Couple, X Ordinary Room, Stayed ...",No pet,"Couple, X Ordinary Room, Stayed 2 nights",other,Leisure trip,Couple,4,Stayed 2 nights,2
...,...,...,...,...,...,...,...,...,...
386786,"Leisure trip, Couple, Superior Double Room, St...",No pet,"Couple, Superior Double Room, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Couple,5,Stayed 2 nights,2
386791,"Business trip, Solo traveler, Superior King Ro...",No pet,"Solo traveler, Superior King Room, Stayed 2 ni...",other,Business trip,Solo traveler,4,Stayed 2 nights,2
386793,"Leisure trip, Group, Junior Suite, Stayed 2 ni...",No pet,"Group, Junior Suite, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Group,5,Stayed 2 nights,2
386798,"Leisure trip, Group, Club Double or Twin Room,...",No pet,"Group, Club Double or Twin Room, Stayed 2 nights",Submitted from a mobile device,Leisure trip,Group,5,Stayed 2 nights,2
386801,"Leisure trip, Solo traveler, Deluxe Double Roo...",No pet,"Solo traveler, Deluxe Double Room, Stayed 2 ni...",other,Leisure trip,Solo traveler,4,Stayed 2 nights,2

In [391]:
tags_a.groupby('duration_of_stay')['tags'].count()

duration_of_stay
                        84
Couple                  62
Stayed 1 night      145373
Stayed 10 nights       663
Stayed 11 nights       306
Stayed 12 nights       217
Stayed 13 nights       174
Stayed 14 nights       184
Stayed 15 nights        87
Stayed 16 nights        38
Stayed 17 nights        27
Stayed 18 nights        24
Stayed 19 nights        23
Stayed 2 nights     100263
Stayed 20 nights        17
Stayed 21 nights        19
Stayed 22 nights         8
Stayed 23 nights         6
Stayed 24 nights         5
Stayed 25 nights         4
Stayed 26 nights         6
Stayed 27 nights        10
Stayed 28 nights         7
Stayed 29 nights         3
Stayed 3 nights      72000
Stayed 30 nights        10
Stayed 4 nights      35748
Stayed 5 nights      15611
Stayed 6 nights       7399
Stayed 7 nights       5549
Stayed 8 nights       1910
Stayed 9 nights        966
Name: tags, dtype: int64

In [321]:
tags_a.count()

tags                386803
pet                 386803
device              230778
trip_type           374614
duration_of_stay    156025
dtype: int64

In [235]:
new_tags[new_tags['device']!='Submitted from a mobile device']['duration_of_stay'].unique()

array(['Submitted from a mobile device', None, 'Stayed 2 nights',
       'Stayed 1 night', 'Stayed 3 nights', 'Stayed 5 nights',
       'Stayed 7 nights', 'Stayed 4 nights', 'Stayed 6 nights',
       'Stayed 9 nights'], dtype=object)

In [ ]:
# На вход данной функции поступает строка с адресом.
def get_tags(tags):

    new_tags = tags.replace(" ']", '')
    new_tags = new_tags.replace("[' ", '')
    new_tags = new_tags.replace("' ", '')
    new_tags = new_tags.replace(" '", '')
    
    tags_list = new_tags.split(', ')[0]
    
    if tags_list[0] == 'With a pet'
        pet = tags_list[0]
    if tags_list[0] != 'With a pet' and tags_list[0] =='Leisure trip' or tags_list[0] =='Business trip'
        pet = None
        trip_type = tags_list[0]
    if tags_list[-1] == 'Submitted from a mobile device'
        device = tags_list[-1]
    if tags_list[-1] != 'Submitted from a mobile device'
        duration_of_stay = tags_list[-1]
    else: none

In [236]:
hotels[['pet','trip_type', 'duration','device']] = hotels['tags'].apply(get_tags),expand=True
hotels

ValueError: Columns must be same length as key

In [220]:
new_tags[new_tags['comma_count']==5]['pet'].unique()

array(['With a pet'], dtype=object)

In [ ]:
# На вход данной функции поступает строка с адресом.
def get_tags(tags):
# Метод split() разбивает строку на слова по пробелу.
# В результате получаем список слов в строке и заносим его в переменную address_list.
    comma_count = tags.count(',')
    tags_list = tags.split(', ')
# Обрезаем список, оставляя в нём только последний элемент,
# потенциальный подтип улицы, и заносим в переменную street_type.
    if comma_count == 5:
        pet = tags_list[0].replace('[^\w\s]','')
        trip_type = tags_list[1].replace('[^\w\s]','')
        traveler = tags_list[2].replace('[^\w\s]','')
        room = tags_list[3].replace('[^\w\s]','')
        duration = tags_list[4].replace('[^\w\s]','')
        device = tags_list[5].replace('[^\w\s]','')
        return pet,trip_type,traveler,room,duration,device
    if comma_count == 4:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        room = tags_list[2].replace('[^\w\s]','')
        duration = tags_list[3].replace('[^\w\s]','')
        device = tags_list[5].replace('[^\w\s]','')
        return trip_type,traveler,room,duration,device
    if comma_count == 3:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        room = tags_list[2].replace('[^\w\s]','')
        return trip_type,traveler,room
    if comma_count == 2:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        return trip_type,traveler
    if comma_count == 1:
        trip_type = tags_list[0].replace('[^\w\s]','')
        return trip_type
    else: None

In [194]:
new_tags['duration_of_stay'].unique()

array(['Stayed 2 nights', 'Stayed 1 night', 'Stayed 3 nights',
       'Stayed 6 nights', 'Stayed 4 nights',
       'Submitted from a mobile device', 'Stayed 5 nights', None,
       'Stayed 8 nights', 'Stayed 7 nights', 'Stayed 10 nights',
       'Stayed 14 nights', 'Stayed 19 nights', 'Standard Double Room',
       'Stayed 13 nights', 'Stayed 9 nights', 'Superior Twin Room',
       'Family Room', 'Stayed 17 nights', 'Stayed 11 nights',
       'Superior Double Room', 'King Room with City View Top floors',
       '2 rooms', 'Double or Twin Room',
       'Executive Double Room Eiffel Studio D Artiste with view of Paris',
       'Deluxe King Room', 'King Room', 'Superior Room',
       'Stayed 12 nights', 'Stayed 15 nights', 'Stayed 21 nights',
       'Stayed 18 nights', 'Double or Twin Room with View',
       'Superior Double or Twin Room with View', 'Suite', 'Double Room',
       'Stayed 16 nights', 'Executive Twin Room', 'Classic Queen Room',
       'Queen Guest Room', 'Standard Room',
       'Classic Room with Courtyard View', 'Twin Room', 'Classic Room',
       'Twin Hilton Guest Room', 'Comfort Family Room',
       'Standard Twin Room', 'Deluxe Double Room', 'Stayed 26 nights',
       'Large Double Room', 'Executive Double or Twin Room',
       'Standard Suite', 'Junior Suite', 'Suite 3 Adults',
       'Special Offer Double Twin Room Stay and Park',
       'Superior Double or Twin Room with Free Wifi', 'Cosy Double Room',
       'Business Double Room', 'Deluxe Studio',
       'Standard Double Room without Window', 'Classic Twin Room',
       'Classic Double or Twin Room', 'penta Standard Room', 'Studio',
       'Superior Triple Room', 'Classic Double Room',
       'Superior King Room', 'Superior Double or Twin Room',
       'Superior Double Room with Spa Access', 'Deluxe Suite',
       'Superior Double Room with Garden View',
       'Luxury Room with Spa Access', 'Deluxe Double or Twin Room',
       'Stayed 30 nights', 'King Hilton Guest Room',
       'Deluxe Double Room with State Opera View',
       'Superior Family Room 2 Adults 1 Child', 'Stayed 22 nights',
       'Executive Double Room', 'Premium Double or Twin Room',
       'Stayed 27 nights', 'Deluxe Single Room', 'Triple Room',
       'Family Room 2 Adults 2 Children', 'Twin Guest Room',
       'Nhow Double or Twin Room', 'Standard Double or Twin Room',
       'Luxury Suite', 'Single Room', 'Comfort Double Room',
       'Deluxe Double or Twin Room 2 adults 1 child',
       'Double or Twin Room 1 2 Adults',
       'Standard Double Room with Park View', 'Standard Queen Room',
       'Standard Room with 1 Double Bed and 1 Sofa Bed',
       'Standard Double or Twin Room Annex Building',
       'Queen Hilton Guest Room', 'Special Offer Deluxe Room',
       'Premium Superior Double Room',
       'Standard Twin Room with 2 single beds',
       'Standard Room with 1 Kingsize Bed',
       'Classic Double Room with City View', 'Executive Room',
       'Family Room 4 People', 'Double Room Non Smoking',
       'Small Double Room', 'Apartment', 'Standard Apartment',
       'City Twin Room', 'Stayed 23 nights', 'Royal Mews View King Room',
       'Stayed 28 nights', 'Executive Triple Room',
       'Business Double or Twin Room', 'Superior Queen Room',
       'Deluxe King Room Balcony with Eiffel Tower View',
       'Club Double Room', 'One Bedroom Suite', 'Deluxe Twin Room',
       'Stayed 20 nights', 'Twin Room Non Smoking',
       'King Room Non Smoking', 'Premium Double Room', 'Double Studio',
       'Deluxe Room', 'Executive King', 'Twin Room Disability Access',
       'Superior Room with Queensize Bed and double couch 2 adults 2 children',
       'Stayed 25 nights', 'Superior Room with Queen Bed',
       'Standard Double',
       'Superior Room with 1 Double Bed and 1 Sofa Bed 1 place',
       'Twin Room with Free Airport Shuttle Service from 5 00am to 00 30am',
       'Studio Double Family', 'Wonderful Double or Twin Room',
       'Standard Room with Spa access', 'Family Room 3 Adults',
       'Duplex Suite with Spa Access', 'Executive King Room',
       'Economy Single Room', 'Studio King Family',
       'Double or Twin Room 1 or 2 adults', 'Deluxe Double Twin Room',
       'City Room', 'Double Guest Room',
       'Deluxe Double Room with Eiffel Tower view',
       'Superior Single Room',
       'Superior Double Room with Two Double Beds',
       'Standard Room with 1 Queen Bed',
       'Junior Suite with Executive Lounge Access',
       'Double Queen Waterfront', 'Executive Studio City View Family',
       'Privilege Double or Twin Room with Spa Access',
       'Classic King Room', 'Park Deluxe Twin',
       'Double or Twin Room Non Smoking',
       'Double Room with Courtyard View', 'Junior Suite 1 2 Adults',
       'Double Room with Two Double Beds',
       'Double or Twin Room with Extra Bed', 'Studio Apartment',
       'Family Room 2 Adults 1 Child', 'Small Single Room',
       'Lower Ground Double Room',
       'Superior Double or Twin Room 1 2 Adults',
       'Superior Double or Twin Room with Garden View',
       'Club Single Room', 'Comfort Double or Twin Room with Rambla View',
       'Tower Suite with Lounge Access', 'Twin Room with Spa Bath',
       'Quadruple Room', 'Double or Twin Room with Courtyard View',
       'Chelsea Double Suite', 'Economy Plus Double Room',
       'Twin Room with Extra Bed', 'King Deluxe Guest Room',
       'Small Double or Twin Room', 'Junior Suite 2 Adults', 'Queen Room',
       'Standard Room with 1 Double Bed', 'Standard Single Room',
       'Economy Double Room', 'Superior Double Room with Internal View',
       'Two Connecting Rooms',
       'Business Apartment with Public Transport Ticket',
       'Stayed 24 nights', 'Amiral Single Room',
       'Comfort Double or Twin Room', 'Double Room with Single Bed',
       'Small Double Room Annex building', '4 Person Suite',
       'penta Plus Room', 'Standard Room with Queen Bed Renovated',
       'Standard Quadruple Room', 'Double Room with Terrace',
       'Junior Deluxe Twin Room', 'Prestige Double Room',
       'Standard Room with Spa Access', 'Single Room Lower Ground Floor',
       'Marina Double Suite', 'Superior King or Twin Room',
       'Deluxe Room Barlow Wing', 'Double Room 1 2 Adults',
       'Executive Room with City View', 'Sextuple Room',
       'Standard Room with Queen Bed', 'Deluxe Double and Single Room',
       'Queen Room Non Smoking', '2 Connecting Rooms 4 Adults',
       'Standard Room with 2 Single Beds', 'Comfort Room',
       'Classic Guest room 1 King or 2 Twin Single Bed s',
       'Premier Double Room', 'Dorsett Double Room',
       'Two Connecting Double Rooms', 'Classic Cosy Room',
       'Classique Double Room',
       'Double Room with Arc de Triomphe View a Glass of Champagne',
       'Superior Double Room Disability Access',
       'Double Hilton Guestroom', 'Superior Twin Room with Terrace',
       'Superior Room with Queen size bed and Sofa Bed',
       'Stayed 29 nights', 'Classic King Twin Room', 'Park Deluxe Suite',
       'Classic Suite', 'Deluxe Eiffel Tower King Room',
       'Superior Double or Twin Room with Terrace',
       'Double Room with City View', 'Small Queen Room',
       'Special Offer Superior Double Room',
       'Deluxe Double or Twin Room with City View',
       'Executive Room 2 adults 2 children', 'Suite with Hot Tub',
       'Quintuple Room', 'Twin Room with Mobile Phone',
       'Superior Room with Double Bed and Sofa Bed',
       'Double Room 2 Adults', 'Superior Room with 1 kingsize bed',
       'Standard', 'Special Offer Double or Twin Room',
       'Duplex Double Room', 'Junior Suite Courtyard',
       'King Suite with Sofa Bed 3 Adults',
       'Superior Room with 1 Queensize Bed and Double Sofa bed',
       'Two Adjacent Double Rooms', 'Superior Queen Room with Sofa Bed',
       'Suite with Spa Access 2 Adults',
       'King Junior Suite with Executive Lounge Access',
       'Deluxe Double Room 1 2 Adults',
       'Executive King Room with Lounge Access',
       'Deluxe King or Twin Room', 'Double Room 1 Adult', 'Studio Suite',
       'Family Room with King Bed and Sofa Bed',
       'Special Offer Queen Room', 'Double Room XL',
       'Deluxe Double Room with Private Patio',
       'Superior Double Twin Room', 'King Guest Room',
       'Luxury Double Room Mezzanine',
       'Duplex Junior Suite with Spa access', 'Premium Room 2 Adults',
       'Comfort Triple Room', 'Premier Twin Room', 'Double Room Annex',
       'Superior Double Room with Balcony and City View',
       'Superior Twin Room with Park View',
       'Executive Double Room with Spa Access',
       'Superior Double Room with Balcony',
       'Family Junior Suite 3 Adults 1 Child', 'Cosy Room',
       'Double Room Disability Access',
       'Double or Twin Room with City View', 'X Ordinary Room',
       'Gallery Suite', 'Queensgate Twin Room',
       'Special Offer Double Room',
       'Classic Double or Twin Room with Spa Access'], dtype=object)

In [193]:
new_tags['duration_of_stay'].nunique()

278

In [147]:
# На вход данной функции поступает строка с адресом.
def get_tags(tags):
# Метод split() разбивает строку на слова по пробелу.
# В результате получаем список слов в строке и заносим его в переменную address_list.
    comma_count = tags.count(',')
    tags_list = tags.split(', ')
# Обрезаем список, оставляя в нём только последний элемент,
# потенциальный подтип улицы, и заносим в переменную street_type.
    if comma_count == 5:
        pet = tags_list[0].replace('[^\w\s]','')
        trip_type = tags_list[1].replace('[^\w\s]','')
        traveler = tags_list[2].replace('[^\w\s]','')
        room = tags_list[3].replace('[^\w\s]','')
        duration = tags_list[4].replace('[^\w\s]','')
        device = tags_list[5].replace('[^\w\s]','')
        return pet,trip_type,traveler,room,duration,device
    if comma_count == 4:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        room = tags_list[2].replace('[^\w\s]','')
        duration = tags_list[3].replace('[^\w\s]','')
        device = tags_list[5].replace('[^\w\s]','')
        return trip_type,traveler,room,duration,device
    if comma_count == 3:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        room = tags_list[2].replace('[^\w\s]','')
        return trip_type,traveler,room
    if comma_count == 2:
        trip_type = tags_list[0].replace('[^\w\s]','')
        traveler = tags_list[1].replace('[^\w\s]','')
        return trip_type,traveler
    if comma_count == 1:
        trip_type = tags_list[0].replace('[^\w\s]','')
        return trip_type
    else: None

In [148]:
hotels[['trip_type', 'traveler', 'room_type', 'duration','device']] = hotels['tags'].apply(get_tags)
hotels

ValueError: Columns must be same length as key

In [121]:
hotels['tags'][28549]

"[' Leisure trip ', ' Travelers with friends ', ' Double or Twin Room ', ' Stayed 4 nights ', ' Submitted from a mobile device ']"

In [ ]:
new_tags = hotels['tags'].split(', ',expand=True)
new_tags

In [123]:
new_tags[0].replace('[^\w\s]','')

0          [' Leisure trip '
1         [' Business trip '
2          [' Leisure trip '
3          [' Leisure trip '
4         [' Business trip '
                 ...
386798     [' Leisure trip '
386799     [' Leisure trip '
386800    [' Business trip '
386801     [' Leisure trip '
386802     [' Leisure trip '
Name: 0, Length: 386803, dtype: object

In [ ]:
hotels[['trip_type', 'traveler', 'room_type', 'duration','device']]= pd.DataFrame(hotels['tags'].tolist(), index=hotels['tags'].index)

In [12]:
#Сколько уникальных тегов представлено в наборе данных?
hotels['tags'].nunique()

47135